version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "pytest", "tests/"]
    environment:
      - PYTHONPATH=/app  # Указываем путь к корневой директории приложения